# Loads default set of integrations. Do not remove.
default_config:

shell_command:
  git_pull_config: "git checkout automations.yaml && git pull >> git.log 2>> git.error.log"


discovery:
api:
http:
  server_port: 443
  ssl_key: /ssl/privkey.pem
  ssl_certificate: /ssl/fullchain.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 2400:cb00::/32
    - 2606:4700::/32
    - 2803:f800::/32
    - 2405:b500::/32
    - 2405:8100::/32
    - 2a06:98c0::/29
    - 2c0f:f248::/32

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
schedule: !include_dir_named schedules
light: !include_dir_list lights
input_datetime: !include_dir_named input_datetimes
timer: !include_dir_named timers

template:
  - timer:
      - name: "Test timer template"
        unique_id: test_timer
        duration: 336:00:00
        icon_template: "{{iif(is_state('timer.test_timer','idle'), 'mdi:washing-machine-alert', 'mdi:receipt') }}"

zha:
  device_config:
    84:71:27:ff:fe:93:17:24-1:    # format: {ieee}-{endpoint_id}
      type: "switch"
  zigpy_config:
    ota:
      ikea_provider: true

recorder:
  purge_keep_days: 5

influxdb:
  api_version: 2
  host: eu-central-1-1.aws.cloud2.influxdata.com
  token: !secret influxdb_token
  organization: harryemartland@gmail.com
  bucket: homeassistant
  include:
    domains:
      - sensor
  exclude:
    entity_globs:
      - sensor.pixel_6*
      - sensor.work_laptop*
      - sensor.*battery*

google_assistant:
  project_id: home-assistant-362521
  report_state: true
  expose_by_default: false
  service_account: !include google_assistant_service_account.json
  entity_config:
    light.spot_light:
      name: Spot Light
      aliases:
        - spot
    light.hall_ceiling_group:
      name: Hall Ceiling Lights
      room: Hall
    light.coffee_lamp:
      name: Coffee Lamp
      room: Hall
