# Loads default set of integrations. Do not remove.
default_config:

shell_command:
  git_pull_config: "git checkout automations.yaml && git pull >> git.log 2>> git.error.log"


discovery:
api:
http:
  server_port: 443
  ssl_key: /ssl/privkey.pem
  ssl_certificate: /ssl/fullchain.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 2400:cb00::/32
    - 2606:4700::/32
    - 2803:f800::/32
    - 2405:b500::/32
    - 2405:8100::/32
    - 2a06:98c0::/29
    - 2c0f:f248::/32

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
schedule: !include_dir_named schedules
light: !include_dir_list lights

zha:
  device_config:
    84:71:27:ff:fe:93:17:24-1:    # format: {ieee}-{endpoint_id}
      type: "switch"
  zigpy_config:
    ota:
      ikea_provider: true

recorder:
  purge_keep_days: 5

influxdb:
  api_version: 2
  host: eu-central-1-1.aws.cloud2.influxdata.com
  token: !secret influxdb_token
  organization: harryemartland@gmail.com
  bucket: homeassistant
  include:
    domains:
      - sensor
  exclude:
    entity_globs:
      - sensor.pixel_6*
      - sensor.work_laptop*
      - sensor.*battery*

google_assistant:
  project_id: home-assistant-362521
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - switch
    - light
  entity_config: