id: hall-sensor
mode: restart
alias: Hall Sensor
trigger:
  - type: motion
    platform: device
    entity_id: binary_sensor.hms1_motion
    device_id: 381d86e848b74e791ccbc32aa58ddb90
    domain: binary_sensor
condition:
  - condition: sun
    after: sunset
action:
  - service: light.turn_on
    target:
      area_id: hall
  - delay: "00:02:00"
  - service: light.turn_off
    target:
      area_id: hall
