id: remote-backup
alias: Remote Backup
trigger:
  platform: state
  entity_id:
    - schedule.backup
  attribute: next_event
action:
  - service: hassio.backup_full
  - service: shell_command.remote_backup