id: return-home
alias: Return Home
trigger:
  - platform: zone
    entity_id: person.harry
    zone: zone.home
    event: enter
condition:
  - condition: sun
    after: sunset
action:
  - service: light.turn_on
    target:
      area_id: living_room
  - service: light.turn_on
    target:
      area_id: hall
