id: turn-off-night
alias: Turn Everything off At Night
trigger:
  platform: time
  at: "00:00:00"
action:
  - service: light.turn_off
    entity_id: all
  - service: switch.turn_off
    entity_id: all
