id: work-event-start
alias: Work Event Started
trigger:
  platform: calendar
  event: start
  offset: "-0:0:0"
  entity_id: calendar.harry_martland_booking_com
condition:
  - condition: zone
    entity_id: person.harry
    zone: zone.home
action:
  service: media_player.play_media
  target:
    entity_id: media_player.living_room_speaker
  data:
    media_content_id: media-source://tts/google_translate?message=Next+meeting+starting+now
    media_content_type: provider
  metadata:
    title: Next meeting starting now
    thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
    media_class: app
    children_media_class: null
    navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Next+meeting+starting+now
